server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bank-card-management

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}
      issuer: ${JWT_ISSUER:bank-card-management}

    card-encryption:
      key: ${CARD_ENCRYPTION_KEY}
      key-version: ${CARD_ENCRYPTION_KEY_VERSION:1}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html